### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by swingcake** [blaise-io/contribution#2] opened 2020-07-30 17:46 UTC
It's just stuck, not performing any operation.

Using the Windows binary provided.

```
$ contribution preview -img img/mod_neko.png

               ██                ██
            ██ ░░ ██          ██ ▓▓ ██
            ██ ░░ ░░ ██ ██ ██ ▒▒ ▓▓ ██
▒▒       ██ ░░ ░░ ░░ ░░ ░░ ░░ ░░ ▒▒ ▓▓ ██       ▒▒
   ▒▒    ██ ░░ ░░ ██ ░░ ░░ ░░ ██ ░░ ▓▓ ██    ▒▒
      ▒▒ ██ ░░ ░░ ░░ ░░ ██ ░░ ░░ ░░ ▓▓ ██ ▒▒
   ▒▒    ██ ░░ ░░ ░░ ██ ░░ ██ ░░ ░░ ▓▓ ██    ▒▒

$ contribution push -img img/mod_neko.png -project swingcake/art -w 23

```

**Comment by blaise-io** [comment] 2020-07-31 15:06
Thanks for reporting. 

Unfortunately I don't have access to a Windows system, so I cannot try to reproduce, but it seems an issue accessing `git` from within the program since preview does work.

1. Is git installed and is it on your path? What does `ssh -vT git@github.com` give you?
2. Does the program consume resources while being stuck?  
3. Does it work when you build the binary yourself? 
   - [Install Go](https://golang.org/dl/)
   - Clone or download project
   - In Contribution project dir, run `go run . push -img img/mod_neko.png -project swingcake/art -w 23`

**Comment by swingcake** [comment] 2020-07-31 16:54
Hi, thanks for the quick response!

> 1. Is git installed and is it on your path? What does `ssh -vT git@github.com` give you?

Yes, it is. And it is in my `PATH`. Also, SSH is correctly set up and the same can be tested as below.

```
$ ssh -T git@github.com
Hi swingcake! You've successfully authenticated, but GitHub does not provide shell access.
```

> 2. Does the program consume resources while being stuck?

I don't think so. Unfortunately, I do not know of any ways of testing it rather than having a view of the task manager.
Is there any way to debug the program?

> 3. Does it work when you build the binary yourself?

It did not. The behaviour is the same as when using the binary provided.

```
$ go run . preview -img image/source/mod_neko.png
go: downloading github.com/nfnt/resize v0.0.0-20180221191011-83c6a9932646
go: downloading github.com/esimov/colorquant v1.0.0

               ██                ██
            ██ ░░ ██          ██ ▓▓ ██
            ██ ░░ ░░ ██ ██ ██ ▒▒ ▓▓ ██
▒▒       ██ ░░ ░░ ░░ ░░ ░░ ░░ ░░ ▒▒ ▓▓ ██       ▒▒
   ▒▒    ██ ░░ ░░ ██ ░░ ░░ ░░ ██ ░░ ▓▓ ██    ▒▒
      ▒▒ ██ ░░ ░░ ░░ ░░ ██ ░░ ░░ ░░ ▓▓ ██ ▒▒
   ▒▒    ██ ░░ ░░ ░░ ██ ░░ ██ ░░ ░░ ▓▓ ██    ▒▒

$ go run . push -img image/source/mod_neko.png -project swingcake/art -w 23

```

**Update:**
I ran the same using `Git Bash`, and now we finally have something which I think is the issue and can be solved.

The following is the error message:
`The filename, directory name, or volume label syntax is incorrect.`

This is indeed a problem with Windows compatibility, and not with git. Possible solution would be to fix strings wherever passed and modify them in accordance with Windows filename syntax.

**Comment by blaise-io** [comment] 2021-01-03 12:25
@swingcake Sorry for the very late reply and thanks for the debug info. I may have fixed the issue (https://github.com/golang/go/issues/21318) in https://github.com/blaise-io/contribution/releases/tag/1.0.1 but I cannot test on Windows. Can you confirm?

**Comment by swingcake** [comment] 2021-01-03 17:20
Oh wow, I wasn't expecting a response but this is a sweet surprise. I went ahead and did what I had to do on my Linux machine last time. Also, thanks for b46650b5b6bc905812e1951528ca4ae15386060c which I noticed but was too lazy to report.

However, it's a new year and that means a new art on my contribution graph haha. I'll try to test it soon on Windows!

**Comment by swingcake** [comment] 2021-05-01 08:02
@blaise-io uh yeah, so about that...
It still doesn't work on Windows :(

**Comment by blaise-io** [comment] 2021-05-01 09:58
@swingcake thanks for letting me know. Still the same error? In the meantime I will figure out some way to debug Windows.

Update: On VirtualBox Win10 I'm running into https://github.com/golang/go/issues/14763. Fixing in 1.0.2.

**Comment by blaise-io** [comment] 2021-05-01 11:36
Fixed in https://github.com/blaise-io/contribution/releases/tag/1.0.2

**Closed as completed by blaise-io** 2021-05-01 11:36 UTC

**Comment by swingcake** [comment] 2021-05-02 00:18
I can confirm that it is now working on Windows, however I can only get it to work through `git bash` and not `cmd`. Not an issue.

The off-by-one error is still there though.
